name: fuel_tracker_app
description: "A new Flutter project."

publish_to: 'none'

version: 6.7.0

environment:
  sdk: ^3.8.1

dependencies:
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  file_picker: ^10.3.3
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_masked_text2: ^0.9.1
  flutter_native_splash: ^2.4.6
  flutter_tts: ^4.2.3
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  get: ^4.7.2
  google_fonts: ^6.3.2
  http: ^1.6.0
  image_picker: ^1.2.0
  intl: ^0.20.2
  latlong2: ^0.9.1
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  remixicon: ^1.4.1
  share_plus: ^12.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  version: ^3.0.2

dependency_overrides:
  vector_math: 2.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/app_icon/icon.png
    - assets/splash/splash_image.png
    - assets/languages/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_icon/icon.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash/splash_image.png"
  android_gravity: center
  android_fullscreen: true
  ios_content_mode: center
  ios_fullscreen: true
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
